import type { Metadata } from "next";
import { cookies } from "next/headers";
import type { PaletteMode } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import "./globals.css";
import { AppThemeProvider } from "@/app/theme/AppThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const modeCookie = cookieStore.get("mc_theme_mode")?.value;
  const initialMode: PaletteMode = modeCookie === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AppThemeProvider initialMode={initialMode}>{children}</AppThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
